name: Windows Setup Script

on:
  push:
    paths:
      - '**/*.ps1'
      - '**/run-windows-setup.yml'
  pull_request:
    paths:
      - '**/*.ps1'
  workflow_dispatch:

jobs:
  run-install:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run setup.ps1
        shell: pwsh
        run: |
          & .\setup.ps1
