name: Test Windows installation script

on:
  push:
    paths:
      - '**/*.ps1'
      - '**/test-windows-install.yml'
  pull_request:
    paths:
      - '**/*.ps1'
  workflow_dispatch:

jobs:
  run-installer:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run install.ps1 and test
        shell: pwsh
        run: |
          & .\install.ps1
          vp-vm info
