name: Test MacOS installation script

on:
  push:
    paths:
      - '**/*.sh'
      - '**/test-macos-install.yml'
  pull_request:
    paths:
      - '**/*.sh'
  workflow_dispatch:

jobs:
  run-installer:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run install.sh and test
        run: |
          sh install.sh
          vp-vm info
